name: DADDYLIVE

on:
  schedule:
    - cron: '0 6 * * *'  # Setiap hari jam 06:00 UTC
  workflow_dispatch:  # Memungkinkan eksekusi manual (di halaman Actions GitHub)

jobs:
  extract-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dateutil python-dotenv

      - name: Run Compiled Script
        run: |
          python m3u.py
        env:
          # Pastikan Anda telah mengatur 'FLARESOLVERR_URL' di GitHub Secrets
          FLARESOLVERR_URL: ${{ secrets.FLARESOLVERR_URL }}

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Stash delle modifiche locali (se presenti)
        run: |
          git diff --quiet || git stash

      - name: Scarica le ultime modifiche dal repository remoto
        run: git pull --rebase origin main

      - name: Ripristina le modifiche stashed (se presenti)
        run: |
          git stash list | grep -q "stash@{0}" && git stash pop || echo "Nessuna modifica da ripristinare"

      - name: Aggiungi i file generati al commit
        run: |
          # Hanya menambahkan file output DLHD
          git add dlhd.m3u daddyliveSchedule.json
          git commit -m "UPDATE: DaddyLive Playlist and Schedule" || echo "Nessuna modifica dari DLHD untuk commit"

      - name: Pusha il cambiamento
        run: git push
