name: AutoFlash
on:
  schedule:
    # Jalan setiap 15 menit
    - cron: '*/15 * * * *'
  workflow_dispatch: # Agar bisa dijalankan manual tombol klik juga

jobs:
  hit-url:
    runs-on: ubuntu-latest
    steps:
      - name: Hit URL Update
        run: |
          curl -L -s --user-agent "Mozilla/5.0 (GitHub Actions)" \
          "https://phinnisi.web.id/m3u/skor/cekker.php?q=update"
          echo "Update Request Sent!"

