name: Trigger livemobox M3U

on:
  # Jalankan manual dari GitHub
  workflow_dispatch:

  # Jalankan otomatis setiap 30 menit
  schedule:
    - cron: "*/15 * * * *"

jobs:
  ping-url:
    runs-on: ubuntu-latest

    steps:
      - name: Call match.php
        run: |
          curl -I https://ogietv.biz.id/m3u/match.php
