name: livemobox.m3u

on:
  schedule:
  - cron: "0,16,32,48 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow

      - name: Run LiveMobox M3U generator
        run: |
          python livemobox_m3u.py

      # =========================
      # COMMIT KE GITHUB
      # =========================
      - name: Commit and push M3U
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add dist/livemobox.m3u
          if [[ `git status --porcelain` ]]; then
            git commit -m "Auto update livemobox.m3u"
            git push
          else
            echo "No changes to commit"
          fi

      # =========================
      # FTP UPLOAD (PASTI ADA FILE)
      # =========================
      - name: Upload livemobox.m3u to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: dist/
