name: Trigger Match + Kirim Playlist ke Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  ping-url:
    runs-on: ubuntu-latest

    steps:
      - name: Download playlist
        run: |
          curl -o playlist.m3u https://ogietv.biz.id/m3u/match.php

      - name: Send playlist to Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument" \
          -F chat_id="${{ secrets.TG_CHAT_ID }}" \
          -F document="@playlist.m3u" \
          -F caption="ðŸ“¡ Playlist terbaru (auto-update) â€” $(date +'%Y-%m-%d %H:%M:%S')"
