name: PPVSort2

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  fetch-streams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install aiohttp
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp
        
    - name: Run script
      run: |
        python ppvsort.py
        
    - name: Commit output
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ppvsort.m3u
        git diff --quiet && git diff --staged --quiet || git commit -m "Update PPV playlist"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
