name: PPVSort2

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  fetch-streams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp playwright

    - name: Install Playwright Browsers
      run: |
        playwright install firefox
        playwright install-deps

    - name: Run Script
      run: |
        python ppvsort.py

    - name: Commit m3u
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ppvsortir.m3u
        git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Auto-update PPV M3U [skip ci]" && git push) || \
          echo "No changes"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
